// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcscvmalziaxafwlgtfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhjc2N2bWFsemlheGFmd2xndGZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MDA3MTgsImV4cCI6MjA2NTM3NjcxOH0.EQCx3o2VgdxIXmuXJ_T27W8eiB7WQsPtvv06MPVhFzI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);